server/src/main/java/com/main21/place/entity/Category.java, server/src/main/java/com/main21/place/entity/PlaceCategory.java
=> ✨ feat: Category Entity 작성

client/.eslintrc.js
props관련 eslint rules로 수정했습니다!!
nav 브랜치로 올릴게요~~!!
=> 📝 docs : eslint props rules 오류 수정

server/src/main/java/com/main21/bookmark/member/entity/MBTI.java, server/src/main/java/com/main21/bookmark/member/entity/Member.java, server/src/main/java/com/main21/bookmark/member/entity/Token.java, server/src/main/java/com/main21/exception/BusinessLogicException.java, server/src/main/java/com/main21/exception/ExceptionCode.java, server/src/main/java/com/main21/member/entity/MBTI.java, server/src/main/java/com/main21/member/entity/Member.java, server/src/main/java/com/main21/member/entity/Token.java, server/src/main/java/com/main21/reserve/controller/ReserveController.java, server/src/main/java/com/main21/reserve/dto/ReserveDto.java, server/src/main/java/com/main21/reserve/entity/Reserve.java, server/src/main/java/com/main21/reserve/service/ReserveService.java
=> ✨ feat: BusinessLogic 작성

server/src/main/java/com/main21/ServerApplication.java, server/src/main/java/com/main21/member/controller/MemberController.java, server/src/main/java/com/main21/member/entity/MBTI.java, server/src/main/java/com/main21/member/entity/Member.java, server/src/main/java/com/main21/util/Auditable.java
* Member Entity 작성
* MBTI Entity 작성
=> ✨ feat : Member Entity 작성

server/src/main/java/com/main21/member/entity/MBTI.java
=> 🐛 fix : Member Entity 오타 수정

server/src/main/java/com/main21/member/entity/MBTI.java, server/src/main/java/com/main21/member/entity/Member.java, server/src/main/java/com/main21/member/entity/Token.java
=> 🐛 fix : 패키지변경 및 연관관계매핑수정

server/src/main/java/com/main21/bookmark/entity/Bookmark.java, server/src/main/java/com/main21/member/entity/Member.java, server/src/main/java/com/main21/review/entity/Review.java
=> ✨ feat : 북마크, 리뷰 엔티티 추가

server/src/main/java/com/main21/place/repository/PlaceRepository.java, server/src/main/java/com/main21/reserve/entity/Reserve.java, server/src/main/java/com/main21/reserve/mapper/ReserveMapper.java, server/src/main/java/com/main21/reserve/repository/ReserveRepository.java, server/src/main/java/com/main21/reserve/service/ReserveService.java
=> ✨ feat : Reserve Create 생성

server/src/main/java/com/main21/member/entity/MBTI.java, server/src/main/java/com/main21/member/entity/Member.java
* Member 연관관계 작성 완료
* Bookmark 연관관계 작성 완료
* Review 연관관계 작성 완료
=> ✨ feat : Member 연관관계 작성 완료

server/src/main/java/com/main21/member/dto/MemberDto.java
=> ✨ feat : Member Dto 작성

server/src/main/java/com/main21/member/dto/AuthDto.java
=> 🐛 fix : AuthDto Response 빌더 패턴 추가

server/src/main/java/com/main21/member/dto/AuthDto.java
=> 🐛 fix : AuthDto 수정 요청사항 반영

server/src/main/java/com/main21/review/entity/dto/ReviewDto.java
=> ✨ feat : Review Dto 작성

server/src/main/java/com/main21/bookmark/dto/BookmarkDto.java
* 북마크 Response 추가
* 최신순 정렬 메서드 추가
=> ✨ feat : 북마크 Dto 추가

client/.eslintrc.js, client/package-lock.json, client/package.json, client/src/pages/SignUp.js
회원가입페이지 기능 구현
+ 기본 레이아웃 구현
+ 유효성 검사
=> sparkles feat : 회원가입페이지 기능구현

client/src/pages/LogIn.js
로그인페이지 구현
+ 기본 레이아웃 구현
+ 유효성 검사
=> sparkles feat : 로그인페이지 구현

client/src/components/Nav.js
=> ✨ feat : nav mockup

client/src/components/ReviewWrite.js
=> ✨ feat : 리뷰 작성 모달창 제작

client/src/components/Modal.js
=> ✨ feat : 마이페이지 모달 창 제작

server/src/main/java/com/main21/reserve/controller/ReserveController.java, server/src/main/java/com/main21/reserve/service/ReserveService.java
=> ✨ feat : 예약 삭제(취소) 기능 구현

server/build.gradle, server/src/main/java/com/main21/config/AwsConfig.java, server/src/main/java/com/main21/file/S3Upload.java, server/src/main/java/com/main21/place/controller/PlaceController.java, server/src/main/java/com/main21/place/controller/PlaceImageController.java, server/src/main/java/com/main21/place/dto/PlaceCategoryDto.java, server/src/main/java/com/main21/place/dto/PlaceImageResponseDto.java, server/src/main/java/com/main21/place/dto/PlaceResponseDto.java, server/src/main/java/com/main21/place/entity/PlaceImage.java, server/src/main/java/com/main21/place/repository/PlaceImageRepository.java, server/src/main/java/com/main21/place/service/FileHandler.java, server/src/main/java/com/main21/place/service/PlaceImageService.java, server/src/main/java/com/main21/place/service/PlaceService.java, server/src/main/java/com/main21/review/repository/ReviewRepositoryImpl.java
=> ✨ feat : 정소 이미지 업로드 구현

server/src/main/java/com/main21/place/controller/PlaceController.java, server/src/main/java/com/main21/place/dto/PlaceCategoryDto.java, server/src/main/java/com/main21/place/dto/PlaceDto.java, server/src/main/java/com/main21/place/entity/Place.java, server/src/main/java/com/main21/place/entity/PlaceCategory.java, server/src/main/java/com/main21/place/repository/CustomPlaceRepository.java, server/src/main/java/com/main21/place/repository/PlaceRepository.java, server/src/main/java/com/main21/place/repository/PlaceRepositoryImpl.java, server/src/main/java/com/main21/place/service/PlaceService.java
공간 전체 조회 getPlaces
공간 카테고리별 조회 getCategory
=> ✨ feat : 공간 조회 기능 구현

client/src/components/Modal.js
=> ✨ feat : 모달창에 기능 추가

server/src/main/java/com/main21/reserve/controller/ReserveController.java, server/src/main/java/com/main21/reserve/service/ReserveService.java, server/src/main/java/com/main21/review/controller/ReviewController.java, server/src/main/java/com/main21/review/service/ReviewService.java
* Reserve, Review patch,Delete CookieValue 추가
=> ✨ feat : Reserve, Review patch,Delete CookieValue 추가

client/src/components/Modal.js
=> ✨ feat : 모달창 상태 기능 추가

client/src/components/Nav.js
=> ✨ feat : nav api 요청 시 배열과 텍스트 위치 변경

server/src/main/java/com/main21/file/FileHandler.java, server/src/main/java/com/main21/file/S3Upload.java, server/src/main/java/com/main21/file/UploadFile.java, server/src/main/java/com/main21/place/controller/PlaceController.java, server/src/main/java/com/main21/place/dto/PlaceResponseDto.java, server/src/main/java/com/main21/place/entity/PlaceImage.java, server/src/main/java/com/main21/place/service/PlaceService.java
=> ♻️ refactor : 장소 이미지 업로드 로직 리팩터링

server/src/main/java/com/main21/place/controller/PlaceController.java, server/src/main/java/com/main21/place/dto/PlaceDto.java, server/src/main/java/com/main21/place/repository/CustomPlaceRepository.java, server/src/main/java/com/main21/place/repository/PlaceRepositoryImpl.java, server/src/main/java/com/main21/place/service/PlaceService.java
공간 조회 Pagination, 무한 스크롤 구현
공간 카테고리별 검색 구현
=> ✨ feat : 공간 조회 및 검색 기능 구현

client/.gitignore, client/src/atoms.js, client/src/components/Fade.js, client/src/components/Map.js, client/src/components/View.js
detail 컴포넌트, map, fade 컴포넌트 구현했습니다 (확인해보고 싶으시면 view만 app.js에 띄워보시면 돼요 view안에 map,fade 들어있어요)
카카오맵에서 콘솔 에러 뜨시면 제가 env 파일로 api 키 저장해서 그런거니 필요하시면 말씀해주세요!! + localhost 3000에서 하셔야 됩니다!!
=> ✨ feat : detail 컴포넌트 구현

client/package-lock.json, client/package.json, client/public/index.html, client/src/components/Category.js
=> ✨ feat : category 구현

server/src/main/java/com/main21/bookmark/controller/BookmarkController.java, server/src/main/java/com/main21/bookmark/repository/BookmarkRepositoryImpl.java, server/src/main/java/com/main21/bookmark/repository/CustomBookmarkRepository.java, server/src/main/java/com/main21/bookmark/service/BookmarkService.java
bookmarkRepository findBookmark Query 삭제
Bookmark Pagination 적용
=> ♻️ refactor : Bookmark Pagination 적용

server/src/main/java/com/main21/file/S3Upload.java, server/src/main/java/com/main21/member/controller/MemberController.java, server/src/main/java/com/main21/member/entity/Member.java, server/src/main/java/com/main21/member/entity/MemberImage.java, server/src/main/java/com/main21/member/repository/MemberImageRepository.java, server/src/main/java/com/main21/member/service/MemberService.java, server/src/main/java/com/main21/place/controller/PlaceController.java, server/src/main/java/com/main21/place/service/PlaceService.java
=> ✨ feat : Member 이미지 업로드 구현

server/src/main/java/com/main21/file/S3Upload.java, server/src/main/java/com/main21/member/controller/MemberController.java, server/src/main/java/com/main21/member/service/MemberService.java, server/src/main/java/com/main21/place/controller/PlaceController.java, server/src/main/java/com/main21/place/service/PlaceService.java
=> ✨ feat : 유저이미지 S3 업로드 구현, 코드 리팩토링

server/src/main/java/com/main21/member/controller/AuthController.java, server/src/main/java/com/main21/payment/dto/Amount.java, server/src/main/java/com/main21/payment/dto/CardInfo.java, server/src/main/java/com/main21/payment/dto/PayApprovalDto.java, server/src/main/java/com/main21/payment/dto/PayCancelDto.java, server/src/main/java/com/main21/payment/dto/PayReadyDto.java, server/src/main/java/com/main21/payment/dto/ReservationInfo.java, server/src/main/java/com/main21/payment/outbox/event/OutBoxEventBuilder.java, server/src/main/java/com/main21/payment/outbox/event/OutboxEvent.java, server/src/main/java/com/main21/payment/outbox/event/ReserveCreated.java, server/src/main/java/com/main21/payment/outbox/event/ReserveEventBuilder.java, server/src/main/java/com/main21/payment/response/Message.java, server/src/main/java/com/main21/payment/service/PaymentService.java, server/src/main/java/com/main21/payment/utils/ObjectMapperUtil.java, server/src/main/java/com/main21/payment/utils/PayConstants.java, server/src/main/java/com/main21/security/config/SecurityConfig.java, server/src/main/java/com/main21/security/utils/JwtTokenUtils.java
=> ✨ feat : 액세스 토큰 디코딩 Utils 추가

server/src/main/java/com/main21/place/controller/PlaceController.java, server/src/main/java/com/main21/place/repository/CustomPlaceRepository.java, server/src/main/java/com/main21/place/repository/PlaceRepositoryImpl.java, server/src/main/java/com/main21/place/service/PlaceService.java
- 공간 상세 검색(최소 금액, 최대 금액, 인원수)
- 공간 전체 타이틀 검색
- 공간 카테고리별 타이틀 검색
=> ✨ feat : Search 기능 구현

server/src/main/java/com/main21/place/controller/PlaceController.java, server/src/main/java/com/main21/place/dto/PlaceResponseDto.java, server/src/main/java/com/main21/place/service/PlaceCategoryService.java, server/src/main/java/com/main21/place/service/PlaceService.java
=> ♻️ refactor : 장소 상세검색 시 카테고리 리스트출력

server/src/main/java/com/main21/reserve/dto/ReserveDto.java, server/src/main/java/com/main21/reserve/repository/ReserveRepositoryImpl.java
- 응답데이터 placeId 추가
- reserveId 순으로 내림차순 정렬
=> ✨ refactor : Reserve 응답 데이터 추가 및 정렬 변경

server/src/main/java/com/main21/bookmark/dto/BookmarkDto.java, server/src/main/java/com/main21/bookmark/repository/BookmarkRepositoryImpl.java
- 응답데이터 placeId 추가
- bookmarkId 순으로 내림차순 정렬
=> ✨ refactor : Bookmark 응답 데이터 추가 및 정렬 변경

client/.eslintrc.js, client/src/App.js, client/src/atoms.js, client/src/components/Category.js, client/src/components/Nav.js, client/src/components/ReservationAsideBar.js, client/src/components/View.js, client/src/pages/Detail.js, client/src/pages/LogIn.js, client/src/pages/Main.js, client/src/pages/MyPage.js, client/src/pages/Register.js, client/src/pages/SignUp.js
nav, category 검색 기능 추가 , api 요청
detail 페이지 구현
모든 페이지 nav 반응(토큰 임시 저장 - 기본 값 삭제 원하시면 주석에 있는 remove 사용하시면 돼요!!)
라우팅
=> ✨ feat : nav, category 수정, 라우팅, detail 페이지 조립, nav 페이지 별 반응 구현

server/src/main/java/com/main21/reserve/controller/ReserveController.java, server/src/main/java/com/main21/reserve/repository/CustomReserveRepository.java, server/src/main/java/com/main21/reserve/repository/ReserveRepositoryImpl.java, server/src/main/java/com/main21/reserve/service/ReserveService.java
=> ✨ refactor : Pagination 적용

client/src/components/Category.js
=> 👽 api : 검색, 카테고리 api요청 엔드포인트 변경

client/.eslintrc.js, client/src/components/MyPageCategoryList.js, client/src/components/MyPageComponent.js, client/src/pages/MyPage.js
=> ✨ feat : 마이페이지 컴포넌트 제작

server/src/main/java/com/main21/member/controller/MemberController.java, server/src/main/java/com/main21/member/dto/MemberDto.java, server/src/main/java/com/main21/member/entity/Member.java, server/src/main/java/com/main21/member/repository/MemberRepository.java, server/src/main/java/com/main21/member/service/MemberService.java
* 마이페이지 유저 정보 조회 리펙토링 - 추후 프로필 이미지 추가 해야함
=> ♻️ refactor :  마이페이지 유저 정보 조회 리펙토링 (추후 프로필 이미지 추가 해야함)

client/src/components/Modal.js, client/src/components/MyPageCategoryList.js, client/src/components/MyPageComponent.js, client/src/components/ReviewWrite.js
=> ✨ feat : 마이페이지 컴포넌트 수정

server/build.gradle, server/src/main/java/com/main21/ServerApplication.java, server/src/main/java/com/main21/batch/entity/Best.java, server/src/main/java/com/main21/batch/process/RankingProcess.java, server/src/main/java/com/main21/batch/repository/BestRepository.java, server/src/main/java/com/main21/batch/repository/CustomBestRepository.java, server/src/main/java/com/main21/batch/repository/CustomBestRepositoryImpl.java, server/src/main/java/com/main21/reserve/entity/MbtiCount.java, server/src/main/java/com/main21/reserve/repository/MbtiCountRepository.java, server/src/main/java/com/main21/reserve/service/ReserveService.java
=> ✨ feat : best mbti batch 기능 추가

client/src/atoms.js, client/src/components/Modal.js, client/src/components/MyPageCategoryList.js, client/src/components/MyPageComponent.js
=> ✨ feat : 글 수정 리코일 연결

client/src/components/RegisterComponents/RegisterCategory.js, client/src/components/RegisterComponents/RegisterImages.js, client/src/components/ReservationComponets/ReservationAsideBar.js, client/src/components/ReservationComponets/ReservationCalendar.js, client/src/pages/Detail.js, client/src/pages/Register.js
=> :recycle: refactor : 오타 수정

client/fake-server/db.json, client/src/atoms.js, client/src/components/Category.js, client/src/components/Fade.js, client/src/components/MainCompo.js, client/src/components/Map.js, client/src/components/Nav.js, client/src/components/ReservationComponets/ReservationAsideBar.js, client/src/components/View.js, client/src/pages/Detail.js, client/src/pages/Main.js
detail, main 구현
-atom 추가
-db.json 메인페이지 데이터, 상세페이지 데이터 추가
-json-server 연결
=> ✨ feat : detail, main 구현

client/src/atoms.js, client/src/components/Category.js, client/src/components/Nav.js
=> ✨ feat : 카테고리 id 중복 수정

server/src/main/java/com/main21/batch/process/RankingProcess.java, server/src/main/java/com/main21/place/entity/Place.java, server/src/main/java/com/main21/reserve/entity/HostingTime.java
1. currentDate -> reserveDate
2. place에 maxSpace 추가 
3. 배치 시간 변경
=> ♻️ refactor : Hosting Time 변수명 변경

client/src/components/Category.js, client/src/components/Fade.js, client/src/components/MainCompo.js, client/src/components/Map.js, client/src/components/Nav.js, client/src/components/View.js, client/src/pages/Detail.js, client/src/pages/Main.js
=> ♻️ refactor : nav,mainpage,detailpage-view 변수 정리

client/src/components/Map.js
=> 🐛 fix : 지도 400에러 수정

client/src/components/Fade.js
=> ✨ feat :캐러셀 버튼 조작 수정

server/src/main/java/com/main21/member/dto/MemberDto.java, server/src/main/java/com/main21/place/dto/PlaceImageDto.java, server/src/main/java/com/main21/place/dto/PlacePostDto.java, server/src/main/java/com/main21/reserve/dto/ReserveDto.java, server/src/main/java/com/main21/review/dto/ReviewDto.java, server/src/main/java/com/main21/validator/NotSpace.java, server/src/main/java/com/main21/validator/NotSpaceValidator.java
=> ✨ feat : 유효성 검증 추가

client/package-lock.json, client/package.json, client/src/components/ReservationComponets/ReservationAsideBar.js, client/src/components/ReservationComponets/ReservationCalendar.js
예약 오류 수정
+ 과거시간 선택 비활성화
+ 예약된 시간 선택 비활성화
=> :recycle: refactor 예약 오류 수정

server/src/main/java/com/main21/reserve/controller/ReserveController.java, server/src/main/java/com/main21/reserve/entity/HostingTime.java, server/src/main/java/com/main21/reserve/entity/TimeStatus.java, server/src/main/java/com/main21/reserve/repository/HostingTimeRepository.java, server/src/main/java/com/main21/reserve/repository/TimeStatusRepository.java, server/src/main/java/com/main21/reserve/service/ReserveService.java
=> ✨ feat : 예약시간 생성 로직

server/src/main/java/com/main21/reserve/entity/TimeStatus.java, server/src/main/java/com/main21/reserve/repository/HostingTimeRepository.java, server/src/main/java/com/main21/reserve/repository/TimeStatusRepository.java, server/src/main/java/com/main21/reserve/service/ReserveService.java
1. HostingTIme 생성 시 재생성 X 
2. maxSpace update 로직 추가
=> ✨ feat : 예약시간 생성 로직2

client/src/components/RegisterComponents/RegisterCategory.js, client/src/components/RegisterComponents/RegisterImages.js, client/src/components/ReservationComponents/ReservationAsideBar.js, client/src/components/ReservationComponents/ReservationBottomButtons.js, client/src/components/ReservationComponents/ReservationCalendar.js, client/src/components/ReservationComponents/ReservationCapacityHandler.js, client/src/pages/Detail.js, client/src/pages/LogIn.js, client/src/pages/Register.js, client/src/pages/SignUp.js
멘토링 후 전체적인 코드 리팩토링
+ 변수명 변경
+ import문 순서 변경
+ 중복되는 코드 함수화
=> :recycle: refactor : 멘토링 후 코드 리팩토링

server/src/main/java/com/main21/reserve/controller/ReserveController.java, server/src/main/java/com/main21/reserve/repository/TimeStatusRepository.java, server/src/main/java/com/main21/reserve/service/ReserveService.java
=> ✨ feat : 예약 maxSpace 구현

server/src/main/java/com/main21/reserve/controller/ReserveController.java, server/src/main/java/com/main21/reserve/entity/CancelReason.java, server/src/main/java/com/main21/reserve/repository/CancelReasonRepository.java, server/src/main/java/com/main21/reserve/service/ReserveService.java
Reserve Cancel 기능 구현(기능 추가 필요)
=> ✨ feat : Reserve Cancel 기능 구현

server/src/main/java/com/main21/reserve/controller/ReserveController.java
=> ♻️ refactor: Reserve Cancel 기능 구현

server/src/main/java/com/main21/reserve/service/ReserveService.java
예약 저장 로직 수정
예약된 시간을 선택하면 예약 저장이 안되도록 수정
=> ♻️ refactor: reserve maxSpace 수정

client/fake-server/db.json, client/src/pages/LogIn.js
로그인 통신 기능 구현
+ axios를 사용한 post 요청
+ 디자인 px에서 rem으로 수정
=> :sparkles: feat : 로그인 통신 기능 구현

client/src/components/Category.js, client/src/components/Fade.js, client/src/components/Map.js, client/src/components/Nav.js, client/src/components/View.js, client/src/pages/Detail.js, client/src/pages/Main.js
styled 위치랑 모듈 구분 줄바꿈 처리만 했어요!!
main 컴포넌트 이름이 place로 바꼈는데 api async await 로 바꾼 뒤에 더 수정해서 올릴게요
=> ♻️ refactor : styled 위치 변경, 모듈 구분

client/src/components/MyPageCategoryList.js, client/src/components/MyPageComponent.js, client/src/components/useMyPage.js
코드 익명함수를 선언해서 사용하는 것으로 교체했습니다.
리팩토링 작업 중입니다!
=> ♻️ refactor : 코드 익명함수 변경 및 함수 훅으로 분리작업

client/fake-server/db.json, client/src/App.js, client/src/pages/LogIn.js, client/src/pages/SignUp.js
회원가입 통신 기능 구현
+ axios를 사용하여 post요청
+ 디자인 수정
=> :sparkles: feat : 회원가입 통신 기능 구현

client/src/atoms.js, client/src/pages/Register.js
=> ✨ feat : 글 수정 페이지 기능 구현

client/src/components/RegisterComponents/RegisterCategory.js
체크된 카테고리 리스트 관리 함수 생성
익명함수 대신 함수 선언
=> :recycle: refactor 체크된 카테고리 리스트 관리 함수 생성

client/src/pages/Register.js
글 등록 페이지 오타수정
detailInformation 에서 detailedInformation으로 수정
=> :recycle: 글 등록 페이지 오타수정

server/src/main/java/com/main21/reserve/controller/ReserveController.java, server/src/main/java/com/main21/reserve/service/ReserveService.java
예약 등록, 예약 수정, 예약 결제 RefreshToken 적용
=> ♻️ refactor: Reserve 도메인 RefreshToken 적용

client/src/pages/Register.js
=> ♻️ refactor : 함수 코드 리팩터링

server/src/main/java/com/main21/bookmark/controller/BookmarkController.java, server/src/main/java/com/main21/bookmark/service/BookmarkService.java
=> ♻️ refactor: Bookmark 도메인 RefreshToken 적용

server/src/main/java/com/main21/review/controller/ReviewController.java, server/src/main/java/com/main21/review/service/ReviewService.java
=> ♻️ refactor: Review 도메인 RefreshToken 적용

client/package-lock.json, client/package.json, client/src/App.js, client/src/components/Nav.js, client/src/pages/Detail.js, client/src/pages/Places.js, client/src/setUpProxy.js
=> ✨ feat : proxy 추가,route 변경

server/src/main/java/com/main21/common/CommonService.java, server/src/main/java/com/main21/member/controller/AuthController.java, server/src/main/java/com/main21/member/service/AuthService.java, server/src/main/java/com/main21/member/service/MemberService.java
=> ♻️ refactor : 반복되어 사용되는 메서드 공통화

client/src/components/MyPageCategoryList.js, client/src/components/ReviewWrite.js, client/src/components/useMyPage.js, client/src/pages/Register.js
♻️ refactor : 코드 리팩터링
axios await 형식으로 수정 및 코드 리팩터링
리뷰 작성 컴포넌트 함수 수정
=> ♻️ refactor : 코드 리팩터링

server/src/main/java/com/main21/bookmark/repository/BookmarkRepository.java, server/src/main/java/com/main21/place/controller/PlaceController.java, server/src/main/java/com/main21/place/dto/PlaceDto.java, server/src/main/java/com/main21/place/dto/PlacePostDto.java, server/src/main/java/com/main21/place/dto/PlaceResponseDto.java, server/src/main/java/com/main21/place/entity/Place.java, server/src/main/java/com/main21/place/repository/PlaceCategoryRepository.java, server/src/main/java/com/main21/place/service/PlaceService.java, server/src/main/java/com/main21/reserve/controller/ReserveController.java, server/src/main/java/com/main21/reserve/repository/HostingTimeRepository.java, server/src/main/java/com/main21/reserve/repository/ReserveRepository.java, server/src/main/java/com/main21/reserve/service/ReserveService.java, server/src/main/java/com/main21/review/repository/ReviewRepository.java, server/src/main/java/com/main21/review/repository/ReviewRepositoryImpl.java, server/src/main/java/com/main21/review/service/ReviewService.java
* 대여 종료시간 추가
* 장소 삭제 ( 호스팅 삭제 시 리뷰, 북마크, 호스팅 타임, 예약 취소 후 상태 변경, mbti count, 예약 상태 변경)
=> ✨ feat : 대여 종료시간 추가, 장소 삭제

server/src/main/java/com/main21/file/FileHandler.java, server/src/main/java/com/main21/file/S3Upload.java, server/src/main/java/com/main21/place/controller/PlaceController.java, server/src/main/java/com/main21/place/dto/PlaceCategoryDto.java, server/src/main/java/com/main21/place/dto/PlacePatchDto.java, server/src/main/java/com/main21/place/service/PlaceCategoryService.java, server/src/main/java/com/main21/place/service/PlaceImageService.java, server/src/main/java/com/main21/place/service/PlaceService.java, server/src/main/java/com/main21/reserve/entity/TimeStatus.java, server/src/main/java/com/main21/reserve/repository/HostingTimeRepository.java, server/src/main/java/com/main21/reserve/service/ReserveService.java
=> ✨ feat : Place 수정

client/src/App.js, client/src/components/Nav.js, client/src/components/NavButton.js, client/src/components/NotFound.js, client/src/components/Place.js, client/src/pages/Places.js
nav 버튼 컴포넌트 분리
404 페이지
maincomponent,maincopo > places, place이름 변경
=> ♻️ refactor : nav 버튼 컴포넌트 분리

client/src/components/MyPageCategoryList.js, client/src/components/useMyPage.js
=> ♻️ refactor : 경로 이름 수정

client/src/pages/LogIn.js, client/src/pages/SignUp.js, client/src/setUpProxy.js
=> 👽 api : signup,login api 연결

client/src/atoms.js, client/src/components/ReservationComponents/ReservationCalendar.js
=>  :bug: fix : 예약 종료날짜 오류 수정

client/src/components/MyPageCategoryList.js, client/src/components/useMyPage.js
=> 👽 api : api 주소값 변경

client/src/atoms.js, client/src/components/ReservationComponents/ReservationCalendar.js
예약 달력 시간 선택 오류 수정
+ 예약 달력 시작 시간 선택 오류 수정
+ 예약 달력 종료 시간 선택 오류 수정
+ 변수명 변경
=> :bug: 예약 달력 시간 선택 오류 수정

server/src/main/java/com/main21/bookmark/controller/BookmarkController.java, server/src/main/java/com/main21/bookmark/entity/Bookmark.java, server/src/main/java/com/main21/place/controller/PlaceController.java, server/src/main/java/com/main21/place/dto/PlaceResponseDto.java, server/src/main/java/com/main21/place/service/PlaceService.java
- Place 응답 데이터 추가
nickName, phoneNumber, address
- 상세 페이지 조회 시 북마크 여부 구현 isBookmark
refreshToken이 존재하지 않으면 무조건 false 반환, refreshToken와 bookmark의 memberId가 같고 bookmark가 존재하면 true 반환
=> ✨ feat : Place 응답 데이터 추가 및 상세 페이지 조회 시 북마크 여부 구현

client/src/components/Review.js, client/src/components/ReviewContainer.js, client/src/pages/Detail.js
=> ✨ feat : 상세페이지 내 리뷰 컴포넌트 제작

client/src/components/RegisterComponents/RegisterImages.js, client/src/pages/Register.js, client/src/setUpProxy.js
=> :sparkles: 글 등록, 수정시 유효성 검사 기능 구현

client/src/components/Category.js, client/src/components/Navigation.js/Nav.js, client/src/components/Navigation.js/NavButton.js, client/src/components/ReservationComponents/ReservationAsideBar.js, client/src/components/View.js, client/src/components/useMyPage.js, client/src/hooks/getAllPlaces.js, client/src/hooks/useAsync.js, client/src/pages/Detail.js, client/src/pages/LogIn.js, client/src/pages/MyPage.js, client/src/pages/Places.js, client/src/pages/Register.js, client/src/pages/SignUp.js, client/src/setUpProxy.js
=> 👽 api : api 경로 수정

server/build.gradle, server/src/main/java/com/main21/ServerApplication.java, server/src/main/java/com/main21/common/CommonService.java, server/src/main/java/com/main21/member/controller/AuthController.java, server/src/main/java/com/main21/member/entity/Member.java, server/src/main/java/com/main21/member/entity/MemberImage.java, server/src/main/java/com/main21/member/service/AuthService.java, server/src/main/java/com/main21/member/service/MemberDbService.java, server/src/main/java/com/main21/member/service/MemberService.java, server/src/main/java/com/main21/reserve/dto/PayReadyDto.java, server/src/main/java/com/main21/reserve/feign/DemoFeignInterceptor.java, server/src/main/java/com/main21/reserve/feign/FeignConfig.java, server/src/main/java/com/main21/reserve/feign/GithubDecoder.java, server/src/main/java/com/main21/reserve/feign/KaKaoFeignClient.java, server/src/main/java/com/main21/reserve/service/ReserveService.java, server/src/main/java/com/main21/reserve/utils/KakaoInfo.java, server/src/main/java/com/main21/reserve/utils/PayConstants.java
* MemberService에서 공통으로 사용되는 메서드를 MemberDbService에 분리하여 의존성을 낮췄습니다!
=> ♻️ refactor : MemberService 공통 메서드 분리

client/src/pages/LogIn.js, client/src/pages/SignUp.js
=> :recycle: refactor : 폴더 이름 변경

server/src/main/java/com/main21/reserve/controller/ReserveController.java, server/src/main/java/com/main21/reserve/dto/ReserveDto.java, server/src/main/java/com/main21/reserve/service/CancelReasonService.java, server/src/main/java/com/main21/reserve/service/HostingTimeService.java, server/src/main/java/com/main21/reserve/service/MbtiCountService.java, server/src/main/java/com/main21/reserve/service/ReserveDbService.java, server/src/main/java/com/main21/reserve/service/ReserveService.java
Reserve service 분리
- CancelReasonService
- HostingTimeService
- MbtiCountService
- ReserveDbService
Reserve 취소 사유 입력 사용 미정 -> 메서드 분리
=> ♻️ refactor: Reserve service 분리

server/src/main/java/com/main21/place/service/PlaceCategoryService.java, server/src/main/java/com/main21/place/service/PlaceService.java, server/src/main/java/com/main21/reserve/service/HostingTimeService.java
1. place와 category 연계 수정
2. place 저장, 수정 로직 수정
=> ♻️ refactor: place 와 category 분리

server/src/main/java/com/main21/review/controller/ReviewController.java, server/src/main/java/com/main21/review/dto/ReviewDto.java, server/src/main/java/com/main21/review/service/ReviewDbService.java, server/src/main/java/com/main21/review/service/ReviewService.java
##기능 추가
* 마이페이지에서 리뷰 조회할 때 대표이미지 추가
=> ✨ feat : 마이페이지에서 리뷰 조회에서 대표이미지 추가

server/src/main/java/com/main21/file/S3Upload.java
=> 🐛 fix : 이미지파일 경로 수정

server/src/main/java/com/main21/review/controller/ReviewController.java, server/src/main/java/com/main21/review/dto/ReviewDto.java, server/src/main/java/com/main21/review/service/ReviewDbService.java, server/src/main/java/com/main21/review/service/ReviewService.java
* Review Service에서 Common Service로 적용되어 있던 것들 리펙토링
=> ♻️ refactor: ReviewDbService 적용

client/src/pages/Register.js, client/src/pages/SignUp.js, client/src/setUpProxy.js
=> :recycle: refactor 비밀번호 정규식 변경

client/package-lock.json, client/package.json, client/src/App.js, client/src/atoms.js, client/src/components/Fade.js, client/src/components/ReservationComponents/ReservationAsideBar.js, client/src/components/View.js, client/src/components/useMyPage.js, client/src/index.js, client/src/pages/Places.js, client/src/pages/Register.js, client/src/pages/SignUp.js
=> 👽 api : api 연결

server/src/main/java/com/main21/place/controller/PlaceController.java, server/src/main/java/com/main21/place/dto/PlacePostDto.java, server/src/main/java/com/main21/place/service/PlaceDbService.java, server/src/main/java/com/main21/place/service/PlaceService.java, server/src/main/java/com/main21/reserve/dto/ReserveDto.java, server/src/main/java/com/main21/reserve/entity/Reserve.java, server/src/main/java/com/main21/reserve/service/HostingTimeService.java, server/src/main/java/com/main21/reserve/service/ReserveDbService.java, server/src/main/java/com/main21/reserve/service/ReserveService.java, server/src/main/java/com/main21/review/service/ReviewDbService.java, server/src/main/java/com/main21/review/service/ReviewService.java
=> ♻️ refactor: DbService 분리 및 날짜 데이터 변경

client/src/components/Review.js, client/src/components/ReviewContainer.js, client/src/components/View.js, client/src/components/useMyPage.js
✨ feat : 리뷰 컨테이너 UI 완성 및 임시 api 연결
=> ✨ feat : 리뷰 컨테이너 UI 완성 및 임시 api 연결

server/src/main/java/com/main21/place/dto/PlaceDto.java, server/src/main/java/com/main21/place/dto/PlacePatchDto.java, server/src/main/java/com/main21/place/dto/PlacePostDto.java, server/src/main/java/com/main21/place/entity/Place.java, server/src/main/java/com/main21/place/service/PlaceService.java, server/src/main/java/com/main21/reserve/service/HostingTimeService.java, server/src/main/java/com/main21/reserve/service/ReserveService.java
- 최대 방 개수(maxSpace) 삭제
- 조회수(view) 삭제
- 예약 시 예약 인원(capacity)이 최대 수용인원(maxSpace)을 넘으면 예약 불가
=> ♻️ refactor: PlaceDto 수정 및 예약 등록 로직 수정

client/src/components/ReservationComponents/ReservationAsideBar.js, client/src/components/Review.js
=> ✨ feat : 리뷰 컴포넌트 내 버튼 및 기능 수정

client/package.json, client/src/components/RegisterComponents/RegisterImages.js, client/src/components/ReservationComponents/ReservationAsideBar.js, client/src/pages/Register.js
+ 이미지 깨짐 현상 오류 수정
+ 예약 완료 시 날짜 초기화
=> :recycle: refactor:  이미지 깨짐 현상 오류 수정

client/package.json, client/src/components/Place.js
=> 🎨 style : 금액 천단위 콤마 구분

client/src/pages/Register.js
=> 글 작성 완료시 메인페이지로 이동

client/src/components/Category.js, client/src/components/Navigation/Nav.js, client/src/components/ReservationComponents/ReservationAsideBar.js, client/src/components/View.js, client/src/pages/Places.js
=> 👽 api : api 수정

client/src/components/Fade.js, client/src/components/ReservationComponents/ReservationAsideBar.js, client/src/components/View.js, client/src/pages/Detail.js, client/src/pages/Places.js
=> 👽 api : detail api 수정

client/src/components/ReservationComponents/ReservationAsideBar.js
=> :recycle: refactor: 천원 단위 표시

server/build.gradle, server/src/main/java/com/main21/helper/MailController.java, server/src/main/java/com/main21/helper/MailService.java
=> ✨ feat : 예약 내역 EmailSender 구현

client/src/components/ReservationComponents/ReservationBottomButtons.js, client/src/pages/SignUp.js, client/src/utils/header.js
회원가입 페이지 유효성 검사 수정
+ 비밀번호 공백 허용 금지
+ 닉네임 공백 허용 금지
=> :sparkles: 회원가입 페이지 유효성 검사 수정

client/src/components/ReservationComponents/ReservationBottomButtons.js, client/src/pages/Detail.js, client/src/setUpProxy.js
=> :recycle: 북마크 기능 수정

client/src/App.js
=> 👽 api : 토큰 리이슈

client/src/components/MyPageCategoryList.js, client/src/components/ReservationComponents/ReservationAsideBar.js, client/src/components/ReviewWrite.js, client/src/components/useMyPage.js
=> 👽 api : 리뷰 관련 api 수정

client/src/atoms.js, client/src/components/ReservationComponents/ReservationBottomButtons.js, client/src/pages/Detail.js, client/src/pages/SignUp.js
=> :sparkles: 북마크 기능 구현

client/src/atoms.js, client/src/components/MyPageCategoryList.js, client/src/components/Review.js, client/src/components/ReviewContainer.js, client/src/components/ReviewWrite.js, client/src/components/useMyPage.js
✨ feat : 리뷰 삭제 기능 등 구현
♻️ refactor : 미사용 아톰 삭제
=> ✨ feat : 리뷰 삭제 기능 등 구현

server/src/main/java/com/main21/bookmark/controller/BookmarkController.java, server/src/main/java/com/main21/bookmark/repository/BookmarkRepositoryImpl.java, server/src/main/java/com/main21/bookmark/service/BookmarkService.java, server/src/main/java/com/main21/helper/MailController.java, server/src/main/java/com/main21/helper/MailService.java, server/src/main/java/com/main21/member/dto/MemberDto.java, server/src/main/java/com/main21/member/entity/Member.java, server/src/main/java/com/main21/place/controller/PlaceController.java, server/src/main/java/com/main21/place/dto/PlaceDto.java, server/src/main/java/com/main21/place/repository/PlaceRepositoryImpl.java, server/src/main/java/com/main21/place/service/PlaceService.java
- Bookmark 리팩토링 및 주석 추가
- Place 리팩토링 및 주석 추가
- MailSender String.format() 코드 수정
=> ♻️ refactor: Bookmark, Place, MailSender 코드 리팩토링

server/src/main/java/com/main21/review/controller/ReviewController.java, server/src/main/java/com/main21/review/dto/ReviewDto.java, server/src/main/java/com/main21/review/entity/Review.java, server/src/main/java/com/main21/review/repository/CustomReviewRepository.java, server/src/main/java/com/main21/review/repository/ReviewRepository.java, server/src/main/java/com/main21/review/repository/ReviewRepositoryImpl.java, server/src/main/java/com/main21/review/service/ReviewDbService.java, server/src/main/java/com/main21/review/service/ReviewService.java
=> ♻️ refactor: Review 코드 리팩토링

client/src/App.js
👽 api : re-issue token
> 이슈 체크리스트
=> 👽 api : re-issue token

client/src/components/MyPageCategoryList.js, client/src/components/ReviewWrite.js, client/src/components/useMyPage.js
✨ feat : 리뷰 수정, 삭제 기능 추가 및 마이페이지 관심장소 북마크 해제 기능 추가
=> ✨ feat : 리뷰 수정, 삭제 기능 추가 및 마이페이지 관심장소 북마크 해제 기능 추가

client/src/components/MyPageCategoryList.js, client/src/components/ReservationComponents/ReservationAsideBar.js, client/src/components/ReservationComponents/ReservationBottomButtons.js, client/src/components/ReservationComponents/ReservationCalendar.js, client/src/components/ReservationComponents/ReservationCapacityHandler.js, client/src/pages/Detail.js, client/src/pages/LogIn.js, client/src/pages/Register.js, client/src/pages/SignUp.js
=> :recycle: 전체적인 ui 수정

client/src/App.js, client/src/components/Fade.js, client/src/components/Navigation/Nav.js, client/src/components/View.js, client/src/pages/SignUp.js
🎨 style : detail style 정리
> 이슈 체크리스트
=> 🎨 style : detail style 정리

client/src/components/MyPageCategoryList.js, client/src/components/MyPageComponent.js, client/src/components/useMyPage.js, client/src/pages/MyPage.js, client/src/pages/Register.js
✨ feat : 마이페이지 이미지 수정 기능 추가 및 마이페이지 화면 겹치지 않도록 수정
=> ✨ feat : 마이페이지 이미지 수정 기능 추가

client/src/App.js, client/src/components/View.js, client/src/pages/Places.js, client/src/pages/SignUp.js
=> 👽 api : detail route

client/src/components/ReservationComponents/ReservationCalendar.js
=> :art: style: 달력 폰트 적용

client/src/atoms.js, client/src/components/Category.js, client/src/components/Fade.js, client/src/components/Navigation/Nav.js, client/src/components/Navigation/NavButton.js, client/src/components/ReviewContainer.js, client/src/pages/Detail.js, client/src/pages/Places.js
🐛 fix : places 데이터 문제, detail 뒤로가기 문제 해결
> 이슈 체크리스트
=> 🐛 fix : places 데이터 문제, detail 뒤로가기 문제 해결

client/src/atoms.js, client/src/components/RegisterComponents/RegisterCategory.js, client/src/components/RegisterComponents/RegisterImages.js, client/src/components/ReservationComponents/ReservationAsideBar.js, client/src/components/ReservationComponents/ReservationCalendar.js, client/src/pages/Detail.js, client/src/utils/categoryData.js
=> :recycle: refactor: 작업 파일 리팩토링 및 달력 오류 해결

client/src/components/MyPageCategoryList.js, client/src/components/MyPageComponent.js, client/src/components/ReviewContainer.js, client/src/components/useMyPage.js, client/src/pages/Register.js
✨ feat : 마이페이지 기능 구현
1. 마이페이지 닉네임 유효성검사/중복검사 완료
2. 마이페이지 내 등록 내역들 이름 클릭시 해당 글로 이동 기능 완료
3. 글 수정하기(사진 등록 안되는 오류만 남음)
4. 마이페이지에서 프로필이미지 변경 기능 완료
=> ✨ feat : 마이페이지 기능 구현

client/src/components/useMyPage.js
=> 🐛 fix : 프로필사진 변경 오류 수정

client/src/components/MyPageCategoryList.js, client/src/components/MyPageComponent.js
✨ feat : 마이페이지 수정하기버튼 커서 포인터 추가
=> ✨ feat : 마이페이지 수정하기버튼 커서 포인터 추가

client/src/components/MyPageCategoryList.js
=> 🐛 fix : 결제 모달 중복 에러 해결

server/src/main/java/com/main21/place/controller/PlaceController.java, server/src/main/java/com/main21/place/dto/PlaceDto.java, server/src/main/java/com/main21/place/dto/PlaceResponseDto.java, server/src/main/java/com/main21/place/entity/Place.java, server/src/main/java/com/main21/place/repository/PlaceImageRepository.java, server/src/main/java/com/main21/place/service/PlaceDbService.java
1. 이미지 조회 수정 
2. Place endTIme -> endTime 수정
=> ♻️ refactor : 이미지 조회 수정

server/src/main/java/com/main21/review/dto/ReviewDto.java, server/src/test/java/com/main21/review/controller/ReviewControllerTest.java
* ReviewController 수정 테스트 코드 작성
=>  ✨ feat : ReviewController 수정  테스트 코드 작성

client/src/components/RegisterComponents/RegisterCategory.js, client/src/components/RegisterComponents/RegisterImages.js, client/src/components/RegisterComponents/useRegisterImages.js, client/src/components/ReservationComponents/ReservationAsideBar.js, client/src/components/ReservationComponents/ReservationBottomButtons.js, client/src/components/ReservationComponents/ReservationCalendar.js, client/src/components/ReservationComponents/ReservationCapacityHandler.js, client/src/components/ReservationComponents/useCalendar.js, client/src/components/ReservationComponents/useReservation.js, client/src/pages/LogIn.js, client/src/pages/Register.js, client/src/setUpProxy.js, client/src/utils/images.js
전체적인 리팩토링 및 예약 당일로 제한
+ register 페이지를 제외한 리팩토링
+ 예약 종료일 예약 시작일 당일로 제한
=> 리팩토링 및 예약 가능 시간 제한

server/src/test/java/com/main21/review/controller/ReviewControllerTest.java
* ReviewController 삭제  테스트 코드 작성
=>  ✨ feat : ReviewController 삭제  테스트 코드 작성

server/src/test/java/com/main21/bookmark/controller/BookmarkControllerTest.java
- bookmark 조회
- bookmark 추가
- bookmark 삭제
=> ✨ feat : Bookmark Test

server/src/main/java/com/main21/place/dto/PlaceCategoryDto.java, server/src/main/java/com/main21/place/dto/PlaceDto.java, server/src/main/java/com/main21/place/repository/PlaceRepositoryImpl.java, server/src/test/java/com/main21/place/controller/PlaceControllerTest.java
- GET 장소 상세 조회
- GET 장소 전체 조회
- GET 장소 카테고리 조회
- POST 장소 상세 검색
- GET 장소 잔체 검색 조회
- GET 장소 카테고리 검색 조회
- GET 장소 마이페이지 조회
- DELETE 장소 삭제
- POST 장소 등록
- PATCH 장소 수정
=> ✨ feat : Place Test 1

client/src/components/MyPageCategoryList.js, client/src/components/useMyPage.js, client/src/pages/Register.js
=> ♻️ refactor : 리팩터링

client/src/App.js
=> 👽 api : re-issue 수정

client/package-lock.json, client/package.json, client/src/App.js, client/src/atoms.js, client/src/components/Category.js, client/src/components/MbtiPlaces.js, client/src/components/Navigation/Nav.js, client/src/components/Navigation/NavButton.js, client/src/components/Place.js, client/src/components/View.js, client/src/pages/Detail.js, client/src/pages/Places.js, client/src/utils/categoryData.js, client/src/utils/payment.js
✨ feat : infiniteScroll 구현
> 이슈 체크리스트
=> ✨ feat : infiniteScroll 구현

server/src/main/java/com/main21/review/dto/ReviewDto.java, server/src/test/java/com/main21/review/controller/ReviewControllerTest.java
* ReviewController 상세페이지 조회  테스트 코드 작성
=>  ✨ feat : ReviewController 상세페이지 조회  테스트 코드 작성

client/src/hooks/useLogin.js, client/src/hooks/useSignUp.js, client/src/pages/LogIn.js, client/src/pages/SignUp.js, client/src/setUpProxy.js
로그인, 회원가입 훅 생성
+ useLogin 파일 및 훅 생성
+ useSiginUp 파일 및 훅 생성
=> :recycle: refactor:  로그인 회원가입 훅 생성

server/src/test/java/com/main21/review/controller/ReviewControllerTest.java
* ReviewController 마이페이지 리뷰  조회  테스트 코드 작성
=>  ✨ feat : ReviewController 마이페이지 리뷰  조회  테스트 코드 작성

server/src/docs/asciidoc/index.adoc, server/src/test/java/com/main21/bookmark/controller/BookmarkControllerTest.java, server/src/test/java/com/main21/bookmark/controller/BookmarkCreateTest.java, server/src/test/java/com/main21/bookmark/controller/BookmarkDeleteTest.java, server/src/test/java/com/main21/bookmark/controller/BookmarkGetTest.java, server/src/test/java/com/main21/place/controller/PlaceControllerTest.java, server/src/test/java/com/main21/place/controller/PlaceDeleteTest.java, server/src/test/java/com/main21/place/controller/PlaceGetTest.java, server/src/test/java/com/main21/place/controller/PlaceSearchTest.java
- Bookmark Test 분리
- Place Test 수정
=> ♻️ refactor: Bookmark Test 분리 및 Place Test 수정

server/src/test/java/com/main21/ServerApplicationTests.java, server/src/test/java/com/main21/review/controller/ReviewControllerTest.java, server/src/test/java/com/main21/review/controller/ReviewDeleteTest.java, server/src/test/java/com/main21/review/controller/ReviewGetTest.java, server/src/test/java/com/main21/review/controller/ReviewPatchTest.java, server/src/test/java/com/main21/review/controller/ReviewPostTest.java
* reviewControllerTest 코드 Post,Delete,Get으로 분리
=> ♻️ refactor : reviewControllerTest 코드 분리 리펙토링

server/src/main/java/com/main21/reserve/controller/ReserveController.java, server/src/test/java/com/main21/reserve/controller/ReserveControllerTest.java, server/src/test/java/com/main21/reserve/controller/ReserveDeleteTest.java, server/src/test/java/com/main21/reserve/controller/ReserveGetTest.java, server/src/test/java/com/main21/reserve/controller/ReservePatchTest.java, server/src/test/java/com/main21/reserve/controller/ReservePaymentTest.java
=> ✨ feat: Reserve Test 기본 구조 작성

client/src/atoms.js, client/src/components/Navigation/NavButton.js, client/src/components/ReservationComponents/ReservationAsideBar.js, client/src/components/ReservationComponents/ReservationCalendar.js, client/src/components/ReservationComponents/useCalendar.js, client/src/components/ReservationComponents/useReservation.js, client/src/hooks/useLogin.js, client/src/pages/Detail.js, client/src/utils/header.js
=> :recycle: refactor: 예약 서버 연결 및 리팩토링

client/src/atoms.js, client/src/components/Category.js, client/src/components/Fade.js, client/src/components/MbtiPlaces.js, client/src/components/MyPageComponents/MyPageCategoryList.js, client/src/components/Navigation/NavButton.js, client/src/components/Place.js, client/src/components/View.js, client/src/hooks/useLogin.js, client/src/hooks/useMyPage.js, client/src/pages/Detail.js, client/src/pages/Places.js
=> 👽 api : api 헤더 수정

client/src/components/MbtiPlaces.js, client/src/components/Navigation/NavButton.js, client/src/components/ReservationComponents/ReservationAsideBar.js, client/src/components/ReservationComponents/useCalendar.js, client/src/hooks/useLogin.js, client/src/pages/Detail.js
=> 👽 api : slots 상태변경

server/src/main/java/com/main21/bookmark/entity/Bookmark.java, server/src/main/java/com/main21/reserve/entity/Reserve.java
- Reserve Entity build id추가
- Bookmark Entity build id추가
=> ♻️ refactor: Reserve, Bookmark Entity build id 추가

client/src/components/MbtiPlaces.js, client/src/components/MyPageComponents/MyPageCategoryList.js, client/src/components/ReservationComponents/useCalendar.js, client/src/pages/Places.js
=> 🐛 fix : 마이페이지 결제 삭제

client/src/components/Category.js, client/src/components/MbtiPlaces.js, client/src/components/Navigation/Nav.js, client/src/components/Navigation/NavButton.js, client/src/components/View.js, client/src/hooks/useLogin.js, client/src/pages/Places.js
=> ♻️ refactor : 주석제거

server/src/test/java/com/main10/bookmark/controller/BookmarkGetTest.java, server/src/test/java/com/main10/reserve/controller/ReserveControllerTest.java, server/src/test/java/com/main10/reserve/controller/ReserveDeleteTest.java, server/src/test/java/com/main10/reserve/controller/ReserveGetTest.java, server/src/test/java/com/main10/reserve/controller/ReservePaymentTest.java, server/src/test/java/com/main10/utils/TimeConfig.java
- Reserve Delete Test
- Reserve Get Test
=> ✨ feat: Reserve Test Delete, Get 구현

server/src/main/java/com/main10/domain/reserve/controller/ReserveController.java, server/src/main/java/com/main10/domain/reserve/dto/ReserveDto.java, server/src/main/java/com/main10/domain/reserve/entity/Reserve.java, server/src/test/java/com/main10/reserve/controller/ReservePatchTest.java, server/src/test/java/com/main10/review/controller/ReviewPatchTest.java
* reserveController 수정 테스트 코드 작성
=> ✨ feat : reserveController 수정 테스트 코드 작성

client/src/App.js, client/src/components/MbtiPlaces.js, client/src/components/MyPageComponents/MyPageCategoryList.js, client/src/components/Navigation/Nav.js, client/src/components/Navigation/NavButton.js, client/src/components/Place.js, client/src/pages/Detail.js, client/src/pages/Places.js, client/src/pages/SignUp.js, client/src/setUpProxy.js, client/src/utils/carouselSetting.js, client/src/utils/categoryButton.js, client/src/utils/categoryData.js
🐛 fix : 무한 스크롤 버튼 호환, 뒤로가기, mbti 로그인 유무 수정
> 이슈 체크리스트
=> 🐛 fix : 무한 스크롤 버튼 호환, 뒤로가기, mbti 로그인 유무 수정

server/src/test/java/com/main10/place/controller/PlacePatchTest.java, server/src/test/java/com/main10/reserve/controller/ReservePatchTest.java, server/src/test/java/com/main10/reserve/controller/ReservePaymentTest.java, server/src/test/java/com/main10/review/controller/ReviewControllerTest.java, server/src/test/java/com/main10/review/controller/ReviewDeleteTest.java, server/src/test/java/com/main10/review/controller/ReviewGetTest.java, server/src/test/java/com/main10/review/controller/ReviewPatchTest.java, server/src/test/java/com/main10/review/controller/ReviewPostTest.java
- Reserve Test 코드 정렬 및 불필요한 코드 삭제
- Place Patch Test endTime 추가
=> ♻️ refactor: Reserve Test 코드 정렬 및 Place Test endTime 추가

client/src/components/ReservationComponents/useReservation.js
🐛 fix : payment 헤더 수정
> 이슈 체크리스트
=> 🐛 fix : payment 헤더 수정

client/src/components/Navigation/NavButton.js, client/src/pages/Places.js
🐛 fix : 로그아웃 observer 오류 수정
> 이슈 체크리스트
=> 🐛 fix : 로그아웃 observer 오류 수정

server/src/docs/asciidoc/index.adoc, server/src/main/java/com/main10/domain/member/dto/AuthDto.java, server/src/main/java/com/main10/domain/member/dto/MemberDto.java, server/src/main/java/com/main10/domain/reserve/controller/ReserveController.java, server/src/main/java/com/main10/domain/reserve/service/ReserveService.java, server/src/test/java/com/main10/reserve/controller/ReserveControllerTest.java, server/src/test/java/com/main10/reserve/controller/ReservePaymentTest.java
- Reserve Controller 수정
- Reserve Service 수정
- Reserve Test 예약 프로세스 2
- Reserve Test 예약 프로세스 3
- index.adoc 작성
=> ✨ feat: Reserve Test 예약 프로세스2, 3 구현

client/src/App.js, client/src/components/Category.js, client/src/components/MbtiPlaces.js, client/src/components/Navigation/Nav.js, client/src/components/Navigation/NavButton.js, client/src/components/Navigation/NavUtils.js, client/src/components/Place.js, client/src/components/View.js, client/src/pages/Detail.js, client/src/pages/Places.js, client/src/utils/categoryButton.js, client/src/utils/payment.js
=> 📝 docs : 주석 제거

client/src/components/MyPageComponents/MyPageCategoryList.js, client/src/components/MyPageComponents/MyPageComponent.js, client/src/components/ReviewComponents/ReviewContainer.js, client/src/components/ReviewComponents/ReviewWrite.js, client/src/hooks/useMyPage.js, client/src/hooks/useRegisterEdit.js
=> ♻️ refactor : 콘솔로그 제거 및 ui 수정

server/src/main/java/com/main10/domain/review/entity/Review.java, server/src/main/java/com/main10/global/util/Auditable.java, server/src/test/java/com/main10/review/controller/ReviewControllerTest.java, server/src/test/java/com/main10/review/controller/ReviewGetTest.java
* reviewController GET 테스트 코드 수정
=>  ♻️ refactor : reviewController GET 테스트 코드 수정

server/src/main/java/com/main10/domain/place/dto/PlaceDto.java, server/src/main/java/com/main10/domain/place/service/PlaceService.java, server/src/main/java/com/main10/domain/review/service/ReviewService.java, server/src/test/java/com/main10/reserve/controller/ReserveGetTest.java
- Place Dto 유효성 검증
- Review Service 주석 수정
=> ♻️ refactor: Place Dto 유효성 검증, Review Service 주석 수정

client/src/hooks/useSignUp.js, client/src/pages/SignUp.js
회원가입 페이지 수정
+ 이름 -> 닉네임으로 수정
+ 회원가입 완료 alert 창 생성
=> :recycle: refactor 회원가입 페이지 수정

client/src/setUpProxy.js, client/src/utils/Modal.js
=> 🎨 style : modal, nav 스타일 수정

.github/workflows/fe-dev.yml
=> 👷 build : 깃허브 액션 테스트

client/src/App.js, client/src/components/MbtiPlaces.js, client/src/components/MyPageComponents/MyPageCategoryList.js, client/src/components/Navigation/NavButton.js, client/src/components/ReservationComponents/ReservationBottomButtons.js, client/src/components/ReservationComponents/useReservation.js, client/src/components/ReviewComponents/ReviewContainer.js, client/src/components/ReviewComponents/ReviewWrite.js, client/src/hooks/useLogin.js, client/src/hooks/useMyPage.js, client/src/hooks/useRegister.js, client/src/hooks/useRegisterEdit.js, client/src/hooks/useSignUp.js, client/src/pages/Detail.js, client/src/pages/Places.js
=> 👽 api : 서버 주소 변경

client/public/index.html
=> 🐛 fix : 카카오 지도 앱키 수정

client/package-lock.json, client/package.json, client/public/index.html
=> 👽 api : env 라이브러리 추가

.github/workflows/fe-dev.yml, client/public/index.html
=> 👽 api : env

client/src/pages/SignUp.js
=> 회원가입 페이지 사이즈 크기 변경

client/src/pages/LogIn.js, client/src/pages/SignUp.js
=> 로그인, 회원가입 페이지 한글로 수정

client/src/components/MyPageComponents/MyPageCategoryList.js, client/src/components/ReviewComponents/ReviewContainer.js, client/src/components/ReviewComponents/ReviewWrite.js, client/src/utils/Modal.js
=> 👽 api : api 주소 수정

client/src/components/Navigation/NavButton.js
=> 🎨 style : nav 마이페이지 원모양

client/src/pages/Detail.js, client/src/pages/SignUp.js
:recycle: refactor 예약 블럭 API 수정
=> :recycle: refactor 예약 블럭 API 수정

client/src/components/MyPageComponents/MyPageCategoryList.js
=> 🐛 fix : 날짜 dayjs로 변경

client/src/App.js
=> refresh token reissue

client/src/components/MyPageComponents/MyPageCategoryList.js, client/src/components/MyPageComponents/MyPageComponent.js
=> ✨ feat : 마이페이지 리스트 디자인 수정

client/src/components/MyPageComponents/MyPageComponent.js, client/src/hooks/useMyPage.js
✨ feat : 마이페이지 프로필 디자인 및 api 수정
=> ✨ feat : 마이페이지 프로필 디자인 및 api 수정

client/src/components/MyPageComponents/MyPageCategoryList.js
=> 👽 api : 마이페이지 결제

client/src/components/MyPageComponents/MyPageComponent.js
=> ✨ feat : 마이페이지 프로필 이미지 변경

client/src/atoms.js, client/src/components/MbtiPlaces.js, client/src/components/Navigation/Nav.js, client/src/hooks/useLogin.js
=> 👽 api : mbti, category 수정

client/src/components/View.js
=> ✨ feat : 글 상세 페이지내 주소 추가

client/src/hooks/useMyPage.js
=> 👽 api : 프로필 사진 변경 api 주소 변경

client/src/components/MyPageComponents/MyPageComponent.js, client/src/hooks/useMyPage.js
=> 👽 api : 프로필 사진 변경 로직 변경

client/src/components/Navigation/Nav.js
=> 👽 api : 검색 수정

client/src/components/MyPageComponents/MyPageCategoryList.js
=> 🐛 fix : 시간 비교 함수 변경

client/src/hooks/useMyPage.js
=> Feat/mypagecompone🐛 fix : 닉네임 변경 버튼 활성화 오류 수정

client/src/components/Navigation/NavButton.js
🐛 fix : 글 수정 클릭 후 페이지 이동 후 글 등록 들어왔을 때 데이터가 남는 오류 수정
=> 🐛 fix : 글 수정 클릭 후 페이지 이동 후 글 등록 들어왔을 때 데이터가 남는 오류 수정

client/src/components/Place.js
=> ✨ feat : 제목 20자 표현 수정

client/src/components/MyPageComponents/MyPageCategoryList.js
=> 🐛 fix : 리뷰 쓰기 활성화 시간 수정

client/src/components/MyPageComponents/MyPageCategoryList.js, client/src/components/Place.js
=> ♻️ refactor : 콘솔로그 제거

client/src/components/ReviewComponents/Review.js
=> 🐛 fix : 리뷰작성일자 오류 수정

client/src/components/MyPageComponents/MyPageCategoryList.js
=> ✨ feat : 결제 상태

client/src/components/ReviewComponents/Review.js
=> 🐛 fix : 리뷰 표기 오류 수정

client/src/components/MyPageComponents/MyPageCategoryList.js
=> 🐛 fix : 예약 취소 텍스트 수정

client/src/hooks/useMyPage.js
=> 🐛 fix : mbti 수정

client/src/components/MyPageComponents/MyPageComponent.js, client/src/components/ReviewComponents/Review.js
🐛 fix : 마이페이지 border 및 리뷰 날짜 표기 수정
=> 🐛 fix : 마이페이지 border 및 리뷰 날짜 표기 수정

client/src/App.js, client/src/components/MbtiPlaces.js
🐛 fix : mbti none, re-issue 수정
=> 🐛 fix : mbti none, re-issue 수정

client/src/components/ScrollToTop.js, client/src/index.js
스크롤 최상단으로 이동 기능 구현
페이지 이동시 스크롤 최상단으로 이동하는 기능 현
=> :sparkles: feat : 스크롤 최상단으로 이동

client/src/components/ReservationComponents/useCalendar.js
예약시간 블럭 오류 수정
reserves 시간 한국시간으로 수정
=> :bug: fix: 예약시간 블럭 오류 수정

client/src/components/MyPageComponents/MyPageCategoryList.js
=> ♻️ refactor : 리뷰 날짜 표기 수정

client/src/pages/Register.js
input 이전기록 삭제
글 등록 페이지 input 이전기록 삭제
=> :recycle: refactor :input 이전기록 삭제

client/src/components/Navigation/NavButton.js, client/src/hooks/useRegister.js
=> :recycle: refactor : 장소등록 페이지 이동시 최대인원 초기화

server/src/main/java/com/main10/domain/bookmark/controller/BookmarkController.java, server/src/main/java/com/main10/domain/bookmark/service/BookmarkService.java, server/src/main/java/com/main10/global/security/config/SecurityConfig.java, server/src/main/resources/static/docs/index.html, server/src/test/java/com/main10/review/controller/ReviewGetTest.java
개발용 서버 배포입니다. 내려받으셔서 각자 원하는 기능을 추가하시면 됩니다. 
(서버에는 심사숙고하여 논의가 되면 올리겠습니다...)
=> 👷 build : 개발용 서버 파일 배포

client/src/App.js, client/src/components/ReservationComponents/ReservationBottomButtons.js
♻️ refactor : 북마크 헤더값 수정 및 콘솔로그 제거
=> ♻️ refactor : 북마크 헤더값 수정 및 콘솔로그 제거

client/src/components/MyPageComponents/MyPageCategoryList.js
=> ✨ feat : 결제 상태 추가

client/src/pages/SignUp.js
회원가입 핸드폰번호 정규식 변경
핸드폰 번호 '-' 필수
=> 회원가입 핸드폰번호 정규식 변경

client/src/App.js, client/src/components/Navigation/NavButton.js
=> 🐛 fix : mbti logout 시 삭제

server/src/main/java/com/main10/domain/member/dto/MemberDto.java, server/src/main/resources/static/docs/index.html
=> ♻️ refactor : memberDto 핸드폰번호 정규식 수정

client/src/components/ReservationComponents/ReservationBottomButtons.js, client/src/components/ReservationComponents/useReservation.js
=> 로그아웃 상태에서 북마크 클릭시 로그인 페이지로 이동

client/src/components/ReservationComponents/useReservation.js
=> 로그아웃 상태에서 예약버튼 클릭시 경고창 기능 추가

client/src/hooks/useRegister.js, client/src/pages/Register.js
=> 글 등록 오류 수정

client/src/components/Navigation/Nav.js, client/src/pages/Places.js
=> ✨ feat : 검색어 잔류

client/src/atoms.js
=> mbti 초기값 변경

server/src/main/java/com/main10/domain/place/controller/PlaceController.java, server/src/main/java/com/main10/domain/place/service/PlaceService.java, server/src/main/java/com/main10/domain/reserve/controller/ReserveController.java, server/src/main/java/com/main10/domain/reserve/dto/ReserveDto.java, server/src/main/java/com/main10/domain/reserve/repository/CustomReserveRepository.java, server/src/main/java/com/main10/domain/reserve/repository/ReserveRepositoryImpl.java, server/src/main/java/com/main10/domain/reserve/service/ReserveDbService.java, server/src/main/java/com/main10/domain/reserve/service/ReserveService.java
- POSTMAN 장소 삭제
토큰 상관 없이 게시글 삭제 가능
- 호스트가 등록한 장소별 예약 내역 조회
호스트가 등록한 장소의 현재 예약 내역, 상태, 예약한 사람 확인 가능
=> ✨ feat : POSTMAN 장소 삭제 및 호스트가 예약 내역 조회

client/src/components/Login/OAuth2RedirectHandler.js, client/src/pages/SignUp.js
=> :bug: fix : 소셜로그인 mbti 반영

client/public/index.html, client/src/components/Login/OAuth2RedirectHandler.js
=> :bug: fix : 소셜로그인 mbti 반영 오류 수정

client/src/components/Login/OAuth2RedirectHandler.js
=> :recycle: refactor: 메서드 변경 및 콘솔 제거

client/src/components/Login/OAuth2RedirectHandler.js
=> :bug: fix : 소셜로그인 토큰 오류 수정

client/src/components/Navigation/NavButton.js, client/src/components/ReservationComponents/ReservationBottomButtons.js
=> :bug: fix : 권한 없을 시 강제 로그아웃
